/* ============================================================
   古籍知識庫 · 書目資料（代表性示意版）
   ⚠ 覆蓋全部十藏子類，書名/作者/朝代為真實古典文獻（公有領域）。
   ⚠ 標記 demo:true 為範例示意：僅收錄節錄或待全文，完整文字以 TXT 匯入後呈現。
   結構：{ id, title, author, dynasty, cat, sub, desc, chapters:[{t,ps}], demo, source }
   ============================================================ */
window.GUJI_BOOKS = [

/* ================= 易藏 ================= */
{ id:"zhouyi", title:"周易", author:"佚名（傳伏羲、文王、周公）", dynasty:"先秦", cat:"yi", sub:"易經", demo:true,
  desc:"群經之首，以卦爻辭闡陰陽變化。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"乾卦第一", ps:["乾：元，亨，利，貞。","初九：潛龍勿用。九二：見龍在田，利見大人。","九五：飛龍在天，利見大人。上九：亢龍有悔。","彖曰：大哉乾元，萬物資始，乃統天。"]},
            {t:"坤卦第二", ps:["坤：元，亨，利牝馬之貞。","象曰：地勢坤，君子以厚德載物。"]}]},
{ id:"zhouyizhuan", title:"周易繫辭傳", author:"傳孔子", dynasty:"先秦", cat:"yi", sub:"易經", demo:true,
  desc:"《十翼》之一，論易理與聖人之道。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"meihuayishu", title:"梅花易數", author:"邵雍（傳）", dynasty:"北宋", cat:"yi", sub:"術數", demo:true,
  desc:"以象數起卦斷事的術數經典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yuanhaiziping", title:"淵海子平", author:"徐子平（傳）", dynasty:"五代宋初", cat:"yi", sub:"術數", demo:true,
  desc:"四柱命理學奠基之作。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"qimen", title:"奇門遁甲", author:"佚名", dynasty:"古代", cat:"yi", sub:"術數", demo:true,
  desc:"三式之一，論奇門排盤與趨避。", source:"公有領域原文 · 範例節錄", chapters:[]},

/* ================= 儒藏 ================= */
{ id:"shijing", title:"詩經", author:"佚名", dynasty:"先秦", cat:"ru", sub:"詩經", demo:true,
  desc:"中國最早詩歌總集，三百零五篇。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"關雎", ps:["關關雎鳩，在河之洲。窈窕淑女，君子好逑。","參差荇菜，左右流之。窈窕淑女，寤寐求之。"]}]},
{ id:"shangshu", title:"尚書", author:"佚名", dynasty:"先秦", cat:"ru", sub:"尚書", demo:true,
  desc:"上古政書，記堯舜至秦穆之詔命。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"liji", title:"禮記", author:"戴聖（輯）", dynasty:"西漢", cat:"ru", sub:"禮經", demo:true,
  desc:"記周代禮制與儒家思想的重要典籍。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"禮運·大同", ps:["大道之行也，天下為公。選賢與能，講信修睦。","故人不獨親其親，不獨子其子，使老有所終，壯有所用，幼有所長。"]}]},
{ id:"zhouli", title:"周禮", author:"佚名", dynasty:"先秦", cat:"ru", sub:"禮經", demo:true,
  desc:"記述周代官制的禮書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yili", title:"儀禮", author:"佚名", dynasty:"先秦", cat:"ru", sub:"禮經", demo:true,
  desc:"記述具體儀節的禮經。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yueji", title:"樂記", author:"佚名", dynasty:"先秦", cat:"ru", sub:"樂經", demo:true,
  desc:"儒家論樂之文，後附《禮記》。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zuozhuan", title:"春秋左傳", author:"左丘明", dynasty:"春秋", cat:"ru", sub:"春秋", demo:true,
  desc:"《春秋》最重要的傳，史學與文學並重。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"gongyangzhuan", title:"春秋公羊傳", author:"公羊高", dynasty:"戰國", cat:"ru", sub:"春秋", demo:true,
  desc:"以義理闡發《春秋》微言大義。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"guliangzhuan", title:"春秋穀梁傳", author:"穀梁赤", dynasty:"戰國", cat:"ru", sub:"春秋", demo:true,
  desc:"以禮法解釋《春秋》的另一傳。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"shuowen", title:"說文解字", author:"許慎", dynasty:"東漢", cat:"ru", sub:"小學", demo:true,
  desc:"中國第一部系統分析字形的字典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"erya", title:"爾雅", author:"佚名", dynasty:"先秦", cat:"ru", sub:"小學", demo:true,
  desc:"最早的詞書，訓詁學之祖。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"lunyu", title:"論語", author:"孔子弟子及再傳弟子", dynasty:"先秦", cat:"ru", sub:"四書", demo:true,
  desc:"儒家核心經典，記孔子言行。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"學而篇第一", ps:["子曰：學而時習之，不亦說乎？有朋自遠方來，不亦樂乎？","曾子曰：吾日三省吾身：為人謀而不忠乎？與朋友交而不信乎？傳不習乎？"]},
            {t:"為政篇第二", ps:["子曰：為政以德，譬如北辰，居其所而眾星共之。"]}]},
{ id:"mengzi", title:"孟子", author:"孟軻", dynasty:"戰國", cat:"ru", sub:"四書", demo:true,
  desc:"儒家亞聖之書，倡性善與王道。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"梁惠王上", ps:["孟子見梁惠王。王曰：叟，不遠千里而來，亦將有以利吾國乎？","孟子對曰：王何必曰利？亦有仁義而已矣。"]}]},
{ id:"daxue", title:"大學", author:"曾參（傳）", dynasty:"先秦", cat:"ru", sub:"四書", demo:true,
  desc:"三綱領八條目，修身治國之學。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"經", ps:["大學之道，在明明德，在親民，在止於至善。","古之欲明明德於天下者，先治其國；欲治其國者，先齊其家。"]}]},
{ id:"zhongyong", title:"中庸", author:"子思（傳）", dynasty:"先秦", cat:"ru", sub:"四書", demo:true,
  desc:"論中和之道與誠。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"第一章", ps:["天命之謂性，率性之謂道，修道之謂教。","中也者，天下之大本也；和也者，天下之達道也。"]}]},
{ id:"baihutongyi", title:"白虎通義", author:"班固（撰）", dynasty:"東漢", cat:"ru", sub:"五經總義", demo:true,
  desc:"東漢白虎觀經學會議的總結。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"xiaojing", title:"孝經", author:"佚名", dynasty:"先秦", cat:"ru", sub:"孝經", demo:true,
  desc:"論孝道之綱領，十三經之一。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"開宗明義", ps:["仲尼居，曾子侍。子曰：先王有至德要道，以順天下，民用和睦，上下無怨。","夫孝，德之本也，教之所由生也。"]}]},
{ id:"zhuziyulei", title:"朱子語類", author:"朱熹（門人輯）", dynasty:"南宋", cat:"ru", sub:"語錄", demo:true,
  desc:"朱熹講學語錄之彙編。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"chuanxilu", title:"傳習錄", author:"王守仁（門人輯）", dynasty:"明", cat:"ru", sub:"語錄", demo:true,
  desc:"王陽明心學語錄。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"sanzijing", title:"三字經", author:"王應麟（傳）", dynasty:"南宋", cat:"ru", sub:"啟蒙蒙學", demo:true,
  desc:"蒙學第一書，三字成句。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"開篇", ps:["人之初，性本善。性相近，習相遠。","苟不教，性乃遷。教之道，貴以專。"]}]},
{ id:"qianziwen", title:"千字文", author:"周興嗣", dynasty:"南朝梁", cat:"ru", sub:"啟蒙蒙學", demo:true,
  desc:"千字不重，四言韻文。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"開篇", ps:["天地玄黃，宇宙洪荒。日月盈昃，辰宿列張。","寒來暑往，秋收冬藏。閏餘成歲，律呂調陽。"]}]},
{ id:"dizigui", title:"弟子規", author:"李毓秀", dynasty:"清", cat:"ru", sub:"啟蒙蒙學", demo:true,
  desc:"童蒙養正、待人接物之規範。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yanshijiaxun", title:"顏氏家訓", author:"顏之推", dynasty:"南北朝", cat:"ru", sub:"修身治家", demo:true,
  desc:"家訓之祖，教子弟立身處世。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zhuzijia", title:"朱子治家格言", author:"朱用純", dynasty:"清", cat:"ru", sub:"修身治家", demo:true,
  desc:"治家修身之格言。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"格言", ps:["黎明即起，灑掃庭除，要內外整潔。","一粥一飯，當思來處不易；半絲半縷，恆念物力維艱。"]}]},
{ id:"caigentan", title:"菜根譚", author:"洪應明", dynasty:"明", cat:"ru", sub:"修身治家", demo:true,
  desc:"處世哲學的格言小品。", source:"公有領域原文 · 範例節錄", chapters:[]},

/* ================= 道藏 ================= */
{ id:"qingjingjing", title:"太上老君說常清靜經", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"洞神部", demo:true,
  desc:"道教清靜養生短經。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"正文", ps:["大道無形，生育天地；大道無情，運行日月；大道無名，長養萬物。","人能常清靜，天地悉皆歸。"]}]},
{ id:"durenjing", title:"度人經（靈寶無量度人上品妙經）", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"洞玄部", demo:true,
  desc:"靈寶派核心經典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yuhuangjing", title:"高上玉皇本行集經", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"洞真部", demo:true,
  desc:"洞真部玉皇經典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"taipingjing", title:"太平經", author:"佚名", dynasty:"東漢", cat:"dao", sub:"太平部", demo:true,
  desc:"早期道教的重要經典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"baopuzi", title:"抱朴子內篇", author:"葛洪", dynasty:"東晉", cat:"dao", sub:"太清部", demo:true,
  desc:"論神仙方術與養生。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"cantongqi", title:"周易參同契", author:"魏伯陽", dynasty:"東漢", cat:"dao", sub:"太玄部", demo:true,
  desc:"丹道之祖，內外丹兼論。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zhengyi", title:"太上正一法文經", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"正一部", demo:true,
  desc:"正一派法籙經典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"kaotianjing", title:"太上老君開天經", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"續道藏", demo:true,
  desc:"見於續道藏，述開天闢地之說。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"daodejing", title:"道德經", author:"老子", dynasty:"春秋", cat:"dao", sub:"藏外", demo:true,
  desc:"道家根本經典，五千言論道與自然。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"道經·第一章", ps:["道可道，非常道；名可名，非常名。","無名，天地之始；有名，萬物之母。"]},
            {t:"德經·第二十五章", ps:["有物混成，先天地生。","人法地，地法天，天法道，道法自然。"]}]},
{ id:"zhuangzi", title:"莊子", author:"莊周", dynasty:"戰國", cat:"dao", sub:"藏外", demo:true,
  desc:"道家莊周之書，寓言汪洋恣肆。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"逍遙遊", ps:["北冥有魚，其名為鯤。鯤之大，不知其幾千里也。","化而為鳥，其名為鵬。鵬之背，不知其幾千里也。"]}]},
{ id:"liezi", title:"列子", author:"列禦寇", dynasty:"戰國", cat:"dao", sub:"藏外", demo:true,
  desc:"道家列子之書，多寓言。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yinfujing", title:"黃帝陰符經", author:"佚名", dynasty:"道教經典", cat:"dao", sub:"藏外", demo:true,
  desc:"論天道人事之機，道教著名短經。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"上篇", ps:["觀天之道，執天之行，盡矣。","天發殺機，移星易宿；地發殺機，龍蛇起陸。"]}]},

/* ================= 佛藏 ================= */
{ id:"xinjing", title:"般若波羅蜜多心經", author:"玄奘譯", dynasty:"唐", cat:"fo", sub:"大藏經", demo:true,
  desc:"般若部最短經典。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"正文", ps:["觀自在菩薩，行深般若波羅蜜多時，照見五蘊皆空，度一切苦厄。","色不異空，空不異色，色即是空，空即是色。"]}]},
{ id:"jin'gangjing", title:"金剛般若波羅蜜經", author:"鳩摩羅什譯", dynasty:"後秦", cat:"fo", sub:"大藏經", demo:true,
  desc:"般若部核心經典，闡「凡所有相皆是虛妄」。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"法會因由分第一", ps:["如是我聞：一時，佛在舍衛國祇樹給孤獨園，與大比丘眾千二百五十人俱。"]},
            {t:"善現啟請分第二", ps:["世尊！善男子、善女人，發阿耨多羅三藐三菩提心，應云何住？云何降伏其心？"]}]},
{ id:"lengyanjing", title:"大佛頂首楞嚴經", author:"般剌密諦譯", dynasty:"唐", cat:"fo", sub:"大藏經", demo:true,
  desc:"禪宗重要經典，論心性與修行。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"huayanjing", title:"大方廣佛華嚴經", author:"實叉難陀譯", dynasty:"唐", cat:"fo", sub:"大藏經", demo:true,
  desc:"華嚴宗根本經典，富麗圓融。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"fahuajing", title:"妙法蓮華經", author:"鳩摩羅什譯", dynasty:"後秦", cat:"fo", sub:"大藏經", demo:true,
  desc:"天台宗根本經典，會三歸一。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"liuzutangjing", title:"六祖壇經", author:"慧能（法海輯）", dynasty:"唐", cat:"fo", sub:"大藏經", demo:true,
  desc:"禪宗六祖說法記錄，唯一稱「經」的中土祖師著述。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"wudeng", title:"五燈會元", author:"普濟", dynasty:"南宋", cat:"fo", sub:"續藏經", demo:true,
  desc:"禪宗燈錄之總集。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"sishierzhang", title:"佛說四十二章經", author:"攝摩騰、竺法蘭譯", dynasty:"東漢", cat:"fo", sub:"乾隆藏", demo:true,
  desc:"最早傳入中國的佛經之一。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"第一章", ps:["佛言：辭親出家，識心達本，解無為法，名曰沙門。"]}]},
{ id:"zhuchuang", title:"竹窗隨筆", author:"袾宏（蓮池大師）", dynasty:"明", cat:"fo", sub:"嘉興藏", demo:true,
  desc:"蓮池大師隨筆，見於嘉興藏。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"baiyujing", title:"百喻經", author:"僧伽斯那撰、求那毗地譯", dynasty:"南朝齊", cat:"fo", sub:"藏外", demo:true,
  desc:"以寓言說法的譬喻經典。", source:"公有領域原文 · 範例節錄", chapters:[]},

/* ================= 子藏 ================= */
{ id:"qiminyaoshu", title:"齊民要術", author:"賈思勰", dynasty:"北魏", cat:"zi", sub:"農家", demo:true,
  desc:"中國現存最早最完整的農書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"nongsang", title:"農桑輯要", author:"司農司（編）", dynasty:"元", cat:"zi", sub:"農家", demo:true,
  desc:"元代官修農書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"sunzi", title:"孫子兵法", author:"孫武", dynasty:"春秋", cat:"zi", sub:"兵家", demo:true,
  desc:"兵學聖典，十三篇論用兵之道。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"始計篇第一", ps:["孫子曰：兵者，國之大事，死生之地，存亡之道，不可不察也。","兵者，詭道也。能而示之不能，用而示之不用。"]},
            {t:"謀攻篇第三", ps:["是故百戰百勝，非善之善者也；不戰而屈人之兵，善之善者也。"]}]},
{ id:"wuzi", title:"吳子", author:"吳起", dynasty:"戰國", cat:"zi", sub:"兵家", demo:true,
  desc:"與《孫子》並稱的兵書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"liutao", title:"六韜", author:"呂望（傳）", dynasty:"先秦", cat:"zi", sub:"兵家", demo:true,
  desc:"託名姜太公的兵書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"hanfeizi", title:"韓非子", author:"韓非", dynasty:"戰國", cat:"zi", sub:"法家", demo:true,
  desc:"法家集大成之作。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"shangjunshu", title:"商君書", author:"商鞅（傳）", dynasty:"戰國", cat:"zi", sub:"法家", demo:true,
  desc:"商鞅變法思想之記錄。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"xunzi", title:"荀子", author:"荀況", dynasty:"戰國", cat:"zi", sub:"諸子", demo:true,
  desc:"儒家中荀學，倡性惡與隆禮。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"mozi", title:"墨子", author:"墨翟", dynasty:"戰國", cat:"zi", sub:"諸子", demo:true,
  desc:"墨家經典，兼愛非攻。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"guiguzi", title:"鬼谷子", author:"鬼谷子（傳）", dynasty:"戰國", cat:"zi", sub:"諸子", demo:true,
  desc:"縱橫家經典，論捭闔與游說。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"jiuzhang", title:"九章算術", author:"佚名", dynasty:"漢", cat:"zi", sub:"算法", demo:true,
  desc:"中國古代最重要的數學著作。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zhoubi", title:"周髀算經", author:"佚名", dynasty:"先秦—漢", cat:"zi", sub:"算法", demo:true,
  desc:"最早的數學天文著作，載勾股定理。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"lunheng", title:"論衡", author:"王充", dynasty:"東漢", cat:"zi", sub:"雜論", demo:true,
  desc:"抨擊虛妄、崇尚實證的論著。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yanthielun", title:"鹽鐵論", author:"桓寬", dynasty:"西漢", cat:"zi", sub:"雜論", demo:true,
  desc:"記昭帝時鹽鐵會議的辯論。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"shishuoxinyu", title:"世說新語", author:"劉義慶", dynasty:"南朝宋", cat:"zi", sub:"筆記", demo:true,
  desc:"魏晉名士風流的筆記小說。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"德行第一", ps:["陳仲舉言為士則，行為世範，登車攬轡，有澄清天下之志。"]}]},
{ id:"mengxibitan", title:"夢溪筆談", author:"沈括", dynasty:"北宋", cat:"zi", sub:"筆記", demo:true,
  desc:"百科全書式筆記。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"liaozhai", title:"聊齋志異", author:"蒲松齡", dynasty:"清", cat:"zi", sub:"筆記", demo:true,
  desc:"志怪短篇小說集。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"taipingyulan", title:"太平御覽", author:"李昉等（編）", dynasty:"北宋", cat:"zi", sub:"類書", demo:true,
  desc:"宋代大型類書。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"yiwenleiju", title:"藝文類聚", author:"歐陽詢等（編）", dynasty:"唐", cat:"zi", sub:"類書", demo:true,
  desc:"唐代類書，事文兼採。", source:"公有領域原文 · 範例節錄", chapters:[]},

/* ================= 史藏 ================= */
{ id:"shiji", title:"史記", author:"司馬遷", dynasty:"西漢", cat:"shi", sub:"正史", demo:true,
  desc:"紀傳體通史鼻祖。此為範例節錄。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"太史公自序", ps:["網羅天下放失舊聞，王跡所興，原始察終，見盛觀衰。","上記軒轅，下至于茲，著十二本紀。"]},
            {t:"項羽本紀·節", ps:["項籍者，下相人也，字羽。籍長八尺餘，力能扛鼎，才氣過人。"]}]},
{ id:"hanshu", title:"漢書", author:"班固", dynasty:"東漢", cat:"shi", sub:"正史", demo:true,
  desc:"第一部斷代史。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"sanguozhi", title:"三國志", author:"陳壽", dynasty:"西晉", cat:"shi", sub:"正史", demo:true,
  desc:"記魏蜀吳三國史事。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zizhitongjian", title:"資治通鑑", author:"司馬光", dynasty:"北宋", cat:"shi", sub:"編年", demo:true,
  desc:"編年體通史巨著。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"周紀一", ps:["初命晉大夫魏斯、趙籍、韓虔為諸侯。","臣光曰：臣聞天子之職莫大於禮，禮莫大於分，分莫大於名。"]}]},
{ id:"zhushu", title:"竹書紀年", author:"佚名", dynasty:"戰國", cat:"shi", sub:"編年", demo:true,
  desc:"魏國史書，出土於汲冢。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"zhanguoce", title:"戰國策", author:"劉向（編）", dynasty:"西漢", cat:"shi", sub:"別史", demo:true,
  desc:"記戰國縱橫家言辭。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"guoyu", title:"國語", author:"左丘明（傳）", dynasty:"先秦", cat:"shi", sub:"別史", demo:true,
  desc:"分國記事的國別史。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"tongjianjishi", title:"通鑑紀事本末", author:"袁樞", dynasty:"南宋", cat:"shi", sub:"紀事本末", demo:true,
  desc:"以事為綱的史書體例之創。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"shuijingzhu", title:"水經注", author:"酈道元", dynasty:"北魏", cat:"shi", sub:"地理", demo:true,
  desc:"以水為綱的地理名著。", source:"公有領域原文 · 範例節錄",
  chapters:[{t:"河水", ps:["黃河之水，出于崑崙之山。","河水又東，逕積石山。"]}]},
{ id:"shanhaijing", title:"山海經", author:"佚名", dynasty:"先秦", cat:"shi", sub:"地理", demo:true,
  desc:"上古地理與神話總集。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"xuxiake", title:"徐霞客遊記", author:"徐弘祖", dynasty:"明", cat:"shi", sub:"地理", demo:true,
  desc:"地理考察遊記。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"gaoshizhuan", title:"高士傳", author:"皇甫謐", dynasty:"西晉", cat:"shi", sub:"傳記", demo:true,
  desc:"隱逸高士之傳記。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"lienvzhuan", title:"列女傳", author:"劉向", dynasty:"西漢", cat:"shi", sub:"傳記", demo:true,
  desc:"古代婦女傳記。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"shitong", title:"史通", author:"劉知幾", dynasty:"唐", cat:"shi", sub:"史評", demo:true,
  desc:"中國第一部史學理論著作。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"dutongjianlun", title:"讀通鑑論", author:"王夫之", dynasty:"明末清初", cat:"shi", sub:"史評", demo:true,
  desc:"以義理評論《通鑑》。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"wuyuechunqiu", title:"吳越春秋", author:"趙曄", dynasty:"東漢", cat:"shi", sub:"載記", demo:true,
  desc:"記吳越興亡之史。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"huayangguozhi", title:"華陽國志", author:"常璩", dynasty:"東晉", cat:"shi", sub:"載記", demo:true,
  desc:"記西南地區方志之祖。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"tangdazhaoling", title:"唐大詔令集", author:"宋敏求（編）", dynasty:"北宋", cat:"shi", sub:"詔令奏議", demo:true,
  desc:"唐代詔令之彙編。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"tongdian", title:"通典", author:"杜佑", dynasty:"唐", cat:"shi", sub:"政書", demo:true,
  desc:"典章制度之通史。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"wenxiantongkao", title:"文獻通考", author:"馬端臨", dynasty:"元", cat:"shi", sub:"政書", demo:true,
  desc:"考索歷代典制的巨著。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"tangliudian", title:"唐六典", author:"李林甫等（撰）", dynasty:"唐", cat:"shi", sub:"職官", demo:true,
  desc:"唐代官制法典。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"sikuquanshu", title:"四庫全書總目提要", author:"紀昀等", dynasty:"清", cat:"shi", sub:"目錄", demo:true,
  desc:"中國最大的目錄學著作。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"huangchaojingshi", title:"皇朝經世文編", author:"賀長齡（編）", dynasty:"清", cat:"shi", sub:"經世文編", demo:true,
  desc:"清代經世致用文章總集。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"dongjingmenghua", title:"東京夢華錄", author:"孟元老", dynasty:"南宋", cat:"shi", sub:"四庫雜史", demo:true,
  desc:"記北宋汴京繁華。", source:"公有領域原文 · 範例節錄", chapters:[]},
{ id:"tiangongkaiwu", title:"天工開物", author:"宋應星", dynasty:"明", cat:"shi", sub:"志存記錄", demo:true,
  desc:"明代工農業技術百科。", source:"公有領域原文 · 範例節錄", chapters:[]}
];

/* 全庫輔助函式 */
window.gujiAllBooks = function(){ return window.GUJI_BOOKS.slice(); };
window.gujiBookById = function(id){
  return window.GUJI_BOOKS.find(function(b){return b.id===id;});
};

/* ============================================================
   真實全庫資料整合
   當 js/books-data.js 已載入（window.GUJI_BOOKS_FULL，13,331 部）
   時，以真實十藏書目取代上方示意書目；每本含 file 指向 /texts/。
   ============================================================ */
(function(){
  if(!window.GUJI_BOOKS_FULL || !window.GUJI_BOOKS_FULL.length) return;
  window.GUJI_BOOKS_FULL.forEach(function(b){
    b.desc = b.desc || (b.cat+" › "+b.sub+(b.dynasty?(" · "+b.dynasty):"")+(b.author?(" · "+b.author):""));
    b.source = "殆知閣公版文本（繁體原文）";
    b.demo = false;
    b.real = true;
  });
  window.GUJI_BOOKS = window.GUJI_BOOKS_FULL;
  window.gujiAllBooks = function(){ return window.GUJI_BOOKS.slice(); };
  var byId={};
  window.GUJI_BOOKS.forEach(function(b){ byId[b.id]=b; });
  window.gujiBookById = function(id){ return byId[id]||null; };
})();
